### ISSUE TITLE
Detect protocol like Client Stats to improve %version.

### ISSUE THREAD

**Issue by HowardZHY** [Bobcat00/ViaVersionStatus#6]
Versions below 1.6.4 are UNKNOWN with ViaVersion-DEV and Protocol Support now.

**Comment by Bobcat00** [comment]
This is what ClientStats does:
```
int version = ProtocolSupportAPI.getProtocolVersion(p).getId();
if (version == -1) {
    return viaVersion.getPlayerVersion(player);
}
return version;
```
This is what ViaVersionStatus does:
```
serverProtocol = via.getServerProtocol(); // Get server info from ViaVersion
clientProtocol = ps.getProtocol(player); // Start with PS client protocol
// If PS ID <= 0 or PS ID >= server ID, use Via instead
if ((clientProtocol.getId() <= 0) ||
    (clientProtocol.getId() >= serverProtocol.getId()))
{
    // Use Via
    clientProtocol = via.getProtocol(player);
}
```
I don't see how ClientStats would be better.

**Comment by Bobcat00** [comment]
```
	MINECRAFT_1_8(47, ProtocolType.PC, "1.8-1.8.9"),
	MINECRAFT_1_7_10(5, ProtocolType.PC, "1.7.6-1.7.10"),
	MINECRAFT_1_7_5(4, ProtocolType.PC, "1.7-1.7.5"),
	MINECRAFT_1_6_4(78, ProtocolType.PC, "1.6.4"),
	MINECRAFT_1_6_2(74, ProtocolType.PC, "1.6.2-1.6.3"),
	MINECRAFT_1_6_1(73, ProtocolType.PC, "1.6-1.6.1"),
	MINECRAFT_1_5_2(61, ProtocolType.PC, "1.5.2"),
	MINECRAFT_1_5_1(60, ProtocolType.PC, "1.5-1.5.1"),
	MINECRAFT_1_4_7(51, ProtocolType.PC, "1.4.7"),
```
Maybe this is the problem. The protocol IDs got reset after 1.6.4. So when running a 1.6.4 client on a 1.8.x server, the test `clientProtocol.getId() >= serverProtocol.getId()` evaluates `78 >= 47` and then attempts to use ViaVersion to get the client protocol ID. I guess ViaVersion no longer supplies that?

I suppose I could put in special tests for the specific 1.6.4 and earlier IDs listed above. I'm not sure if that would solve the problem.

It should be noted that 1.6.4 is over 9 years old, and it's questionable if we should even bother dealing with it anymore, not to mention that ProtocolSupport appears to be abandoned.

**Comment by HowardZHY** [comment]
um I just wanna excute 
/say %player is using %version
on join, but 1.6.4 and below are just UNKNOWN now...
