### ISSUE TITLE
Only show message on specific versions

### ISSUE THREAD

**Issue by joshwenke** [Bobcat00/ViaVersionStatus#7]
Hello, I am running my server on 1.19.3, but when a player joins with 1.19.2 they are sent a message. I would like to only send a message when someone's version is below a specific threshold. For example, of course 1.8 players should get the message. But it would be nice to not show it to those running 1.17 or 1.18, since they will not really have any problems (besides a couple missing mobs/blocks). On my server it's more significant for older versions since they don't support the Y-coordinate used in our spawns, HEX colors, and other things.

**Comment by EdyDeveloper** [comment]
If it is THAT broken you can always disable those versions from being able to join.

**Comment by joshwenke** [comment]
Thanks. We ended up running a command and handling it there.

**Comment by EdyDeveloper** [comment]
What command did you run? The plugin doesn't really work for me on 1.20.1 and I was trying to figure out another way to do it.
